### PR TITLE
Merge pull request #93 from azhadolfo/andulan-repo

### PR DESCRIPTION
**Pull request by crisleo14**
Andulan repo

### CODE REVIEW

**Comment by crisleo14** [comment]
lupit mo talaga los mineku mekus mo na yan

**Comment by azhadolfo** [comment]
minekus mekus ba naman ni insan mala tornao

**Comment by azhadolfo** [comment]
@crisleo14

**Comment by azhadolfo** [comment]
### TORNADOOOOOO

**Comment by azhadolfo** [comment]
`Console.WriteLine("Hello Insan");`

**Comment by crisleo14** [comment]
### **bangis mo talaga**

**Comment by crisleo14** [comment]
**bangis**

**Comment by azhadolfo** [comment]
>Insan unsint a message.

**Comment by crisleo14** [comment]
awdfqg

**Comment by crisleo14** [comment]
>bangis mo na insan

**Comment by crisleo14** [comment]
asdas

**Comment by crisleo14** [comment]
asdas

**Comment by azhadolfo** [comment]
image

**Comment by crisleo14** [comment]
asdas

**Comment by crisleo14** [comment]
asdsad

**Pull request merged**
